// Code generated by MockGen. DO NOT EDIT.
// Source: ./shortener.go

// Package mock is a generated GoMock package.
package mock

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortenerHandler is a mock of ShortenerHandler interface.
type MockShortenerHandler struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerHandlerMockRecorder
}

// MockShortenerHandlerMockRecorder is the mock recorder for MockShortenerHandler.
type MockShortenerHandlerMockRecorder struct {
	mock *MockShortenerHandler
}

// NewMockShortenerHandler creates a new mock instance.
func NewMockShortenerHandler(ctrl *gomock.Controller) *MockShortenerHandler {
	mock := &MockShortenerHandler{ctrl: ctrl}
	mock.recorder = &MockShortenerHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerHandler) EXPECT() *MockShortenerHandlerMockRecorder {
	return m.recorder
}

// CreateShortURL mocks base method.
func (m *MockShortenerHandler) CreateShortURL(body string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", body)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockShortenerHandlerMockRecorder) CreateShortURL(body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockShortenerHandler)(nil).CreateShortURL), body)
}

// CreateShortURLjson mocks base method.
func (m *MockShortenerHandler) CreateShortURLjson(body io.ReadCloser) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURLjson", body)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURLjson indicates an expected call of CreateShortURLjson.
func (mr *MockShortenerHandlerMockRecorder) CreateShortURLjson(body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURLjson", reflect.TypeOf((*MockShortenerHandler)(nil).CreateShortURLjson), body)
}

// GetShortURL mocks base method.
func (m *MockShortenerHandler) GetShortURL(pathURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortURL", pathURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortURL indicates an expected call of GetShortURL.
func (mr *MockShortenerHandlerMockRecorder) GetShortURL(pathURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortURL", reflect.TypeOf((*MockShortenerHandler)(nil).GetShortURL), pathURL)
}

// RandomID mocks base method.
func (m *MockShortenerHandler) RandomID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandomID")
	ret0, _ := ret[0].(string)
	return ret0
}

// RandomID indicates an expected call of RandomID.
func (mr *MockShortenerHandlerMockRecorder) RandomID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomID", reflect.TypeOf((*MockShortenerHandler)(nil).RandomID))
}
